# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Input_2 = QtWidgets.QFrame(self.centralwidget)
        self.Input_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Input_2.setLineWidth(2)
        self.Input_2.setMidLineWidth(5)
        self.Input_2.setObjectName("Input_2")
        self.gridLayout = QtWidgets.QGridLayout(self.Input_2)
        self.gridLayout.setObjectName("gridLayout")
        self.table_of_contents_3 = QtWidgets.QLabel(self.Input_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.table_of_contents_3.setFont(font)
        self.table_of_contents_3.setObjectName("table_of_contents_3")
        self.gridLayout.addWidget(self.table_of_contents_3, 0, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.Input_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 2, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.Input_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.Input_2)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.Input_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setTabletTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.progressBar_3 = QtWidgets.QProgressBar(self.Input_2)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout.addWidget(self.progressBar_3, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.Input_2)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.Input_2, 0, 0, 1, 1)
        self.func = QtWidgets.QFrame(self.centralwidget)
        self.func.setFrameShape(QtWidgets.QFrame.Box)
        self.func.setFrameShadow(QtWidgets.QFrame.Raised)
        self.func.setLineWidth(2)
        self.func.setMidLineWidth(5)
        self.func.setObjectName("func")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.func)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.func)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 1, 1, 1, 2)
        self.table_of_contents_2 = QtWidgets.QLabel(self.func)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.table_of_contents_2.setFont(font)
        self.table_of_contents_2.setObjectName("table_of_contents_2")
        self.gridLayout_2.addWidget(self.table_of_contents_2, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.func)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setTabletTracking(False)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.func)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 2, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.func)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 3, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.func)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.func)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_2.addWidget(self.progressBar_2, 4, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.func)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.func)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 2, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.func)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 4)
        self.gridLayout_3.addWidget(self.func, 0, 1, 1, 1)
        self.Visual = QtWidgets.QTabWidget(self.centralwidget)
        self.Visual.setTabPosition(QtWidgets.QTabWidget.North)
        self.Visual.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Visual.setIconSize(QtCore.QSize(20, 20))
        self.Visual.setElideMode(QtCore.Qt.ElideNone)
        self.Visual.setUsesScrollButtons(True)
        self.Visual.setTabBarAutoHide(True)
        self.Visual.setObjectName("Visual")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(10, 10, 341, 251))
        self.widget_4.setObjectName("widget_4")
        self.Visual.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.Visual.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.Visual, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Visual.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.table_of_contents_3.setText(_translate("MainWindow", "Блок ввода"))
        self.radioButton_3.setText(_translate("MainWindow", "Vk"))
        self.radioButton_4.setText(_translate("MainWindow", "Facebook"))
        self.pushButton_3.setText(_translate("MainWindow", "Кнопка когда выберут соц сеть "))
        self.label.setText(_translate("MainWindow", "Ввод данных->"))
        self.table_of_contents_2.setText(_translate("MainWindow", "Блок фишек"))
        self.label_2.setText(_translate("MainWindow", "выберите->"))
        self.comboBox.setItemText(0, _translate("MainWindow", "поиски всякие"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Новый элемент"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Новый элемент"))
        self.label_3.setText(_translate("MainWindow", "search time:"))
        self.label_6.setText(_translate("MainWindow", "что то еще?"))
        self.pushButton_2.setText(_translate("MainWindow", "click to make something happen"))
        self.label_5.setText(_translate("MainWindow", "number of something to search for something"))
        self.Visual.setTabText(self.Visual.indexOf(self.widget), _translate("MainWindow", "Граф"))
        self.Visual.setTabText(self.Visual.indexOf(self.tab_2), _translate("MainWindow", "Таблица"))
